name: flutter_fgbg_module
description: "This is a module that notifies you when the app goes into the background or comes to the foreground"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/flutter_fgbg_module

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  flutter_fgbg:  #@add
  easy_event_bus:  #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true